### ISSUE TITLE
[Bug] Wrong default extension

### ISSUE THREAD

**Issue by darthdemono** [amir1376/ab-download-manager-browser-integration#5]
### Issue:

The application currently uses the ".gzip" file extension by default, but this is incorrect as the standard extension for gzip files is ".gz". 

### Simple Fix: 

- **Remove** the ".gzip" extension from the default settings.
- **Add** the ".gz" extension as the default for gzip-compressed files.

**Comment by amir1376** [comment]
@darthdemono Thanks for mentioning that, I will fix this
